import 'dotenv/config';
import { ServiceStatus } from '../generated/prisma/client.js';
import { prisma } from '../src/lib/prisma.js';

async function main() {
  console.log('🌱 Iniciando seed...');

  await prisma.service.deleteMany();
  await prisma.client.deleteMany();

  const client1 = await prisma.client.create({
    data: {
      name: 'João Silva',
      address: 'Rua das Flores, 123 - Centro',
      phone_number: '34999991111',
    },
  });

  const client2 = await prisma.client.create({
    data: {
      name: 'Maria Oliveira',
      address: 'Av. Brasil, 500 - Ap 202',
      phone_number: '34888882222',
    },
  });

  const client3 = await prisma.client.create({
    data: {
      name: 'Carlos Santos',
      address: 'Rua Amazonas, 89 - Bairro Sul',
      phone_number: '34777773333',
    },
  });

  const client4 = await prisma.client.create({
    data: {
      name: 'Ana Costa',
      address: 'Alameda dos Anjos, 404 - Casa 2',
      phone_number: '34666664444',
    },
  });

  const client5 = await prisma.client.create({
    data: {
      name: 'Roberto Almeida',
      address: 'Praça da República, 10 - Cobertura',
      phone_number: '34555555555',
    },
  });

  await prisma.service.createMany({
    data: [
      {
        client_id: client1.id,
        furniture_name: 'Sofá 3 Lugares',
        fabric_name: 'Linho Cinza',
        fabric_code: 'LN-042',
        fabric_price_per_meter: 45.0,
        fabric_meters: 12.5,
        cost_fabric: 562.5,
        cost_foam: 200.0,
        cost_labor: 800.0,
        cost_shipping: 100.0,
        cost_other: 50.0,
        total_cost: 1712.5,
        final_price: 2800.0,
        net_profit: 1087.5,
        collection_date: new Date('2025-10-10'),
        delivery_date: new Date('2025-10-25'),
        status: ServiceStatus.PAID,
        notes: 'Cliente pediu para reforçar as percintas.',
      },
      {
        client_id: client1.id,
        furniture_name: 'Cadeira de Jantar (6x)',
        fabric_name: 'Suede Bege',
        fabric_code: 'SD-B',
        fabric_price_per_meter: 35.0,
        fabric_meters: 6.0,
        cost_fabric: 210.0,
        cost_foam: 150.0,
        cost_labor: 600.0,
        cost_shipping: 80.0,
        cost_other: 0.0,
        total_cost: 1040.0,
        final_price: 1800.0,
        net_profit: 760.0,
        collection_date: new Date('2026-02-10'),
        delivery_date: new Date('2026-02-20'),
        status: ServiceStatus.DELIVERED,
      },
      {
        client_id: client1.id,
        furniture_name: 'Puff Quadrado',
        fabric_name: 'Couro Sintético',
        fabric_code: 'CS-01',
        fabric_price_per_meter: 50.0,
        fabric_meters: 2.0,
        cost_fabric: 100.0,
        cost_foam: 50.0,
        cost_labor: 150.0,
        cost_shipping: 30.0,
        cost_other: 10.0,
        total_cost: 340.0,
        final_price: 600.0,
        net_profit: 260.0,
        collection_date: new Date('2026-03-01'),
        status: ServiceStatus.COMPLETED,
      },
      {
        client_id: client2.id,
        furniture_name: 'Poltrona de Leitura',
        fabric_name: 'Veludo Azul',
        fabric_code: 'VL-AZ',
        fabric_price_per_meter: 60.0,
        fabric_meters: 4.5,
        cost_fabric: 270.0,
        cost_foam: 120.0,
        cost_labor: 400.0,
        cost_shipping: 60.0,
        cost_other: 20.0,
        total_cost: 870.0,
        final_price: 1450.0,
        net_profit: 580.0,
        collection_date: new Date('2025-12-15'),
        delivery_date: new Date('2025-12-28'),
        status: ServiceStatus.PAID,
        notes: 'Trocar pés de madeira por metal.',
      },
      {
        client_id: client2.id,
        furniture_name: 'Cabeceira de Cama (Casal)',
        fabric_name: 'Linho Cru',
        fabric_code: 'LN-CR',
        fabric_price_per_meter: 40.0,
        fabric_meters: 3.0,
        cost_fabric: 120.0,
        cost_foam: 90.0,
        cost_labor: 250.0,
        cost_shipping: 50.0,
        cost_other: 15.0,
        total_cost: 525.0,
        final_price: 900.0,
        net_profit: 375.0,
        collection_date: new Date('2026-02-05'),
        delivery_date: new Date('2026-02-15'),
        status: ServiceStatus.PAID,
      },
      {
        client_id: client2.id,
        furniture_name: 'Recamier',
        fabric_name: 'Suede Marrom',
        fabric_code: 'SD-M',
        fabric_price_per_meter: 32.0,
        fabric_meters: 4.0,
        cost_fabric: 128.0,
        cost_foam: 80.0,
        cost_labor: 350.0,
        cost_shipping: 50.0,
        cost_other: 0.0,
        total_cost: 608.0,
        final_price: 1100.0,
        net_profit: 492.0,
        collection_date: new Date('2026-03-02'),
        status: ServiceStatus.IN_PROGRESS,
      },
      {
        client_id: client3.id,
        furniture_name: 'Sofá Retrátil 4 Lugares',
        fabric_name: 'Animale Chumbo',
        fabric_code: 'AN-CH',
        fabric_price_per_meter: 55.0,
        fabric_meters: 18.0,
        cost_fabric: 990.0,
        cost_foam: 400.0,
        cost_labor: 1200.0,
        cost_shipping: 150.0,
        cost_other: 100.0,
        total_cost: 2840.0,
        final_price: 4500.0,
        net_profit: 1660.0,
        collection_date: new Date('2025-08-10'),
        delivery_date: new Date('2025-08-30'),
        status: ServiceStatus.PAID,
        notes: 'Molas ensacadas no assento.',
      },
      {
        client_id: client3.id,
        furniture_name: 'Poltrona do Papai',
        fabric_name: 'Couro Natural',
        fabric_code: 'CN-PT',
        fabric_price_per_meter: 150.0,
        fabric_meters: 5.0,
        cost_fabric: 750.0,
        cost_foam: 200.0,
        cost_labor: 600.0,
        cost_shipping: 80.0,
        cost_other: 50.0,
        total_cost: 1680.0,
        final_price: 3200.0,
        net_profit: 1520.0,
        collection_date: new Date('2026-02-15'),
        delivery_date: new Date('2026-02-28'),
        status: ServiceStatus.DELIVERED,
      },
      {
        client_id: client3.id,
        furniture_name: 'Almofadas (10x)',
        fabric_name: 'Linho Estampado',
        fabric_code: 'LN-EST',
        fabric_price_per_meter: 45.0,
        fabric_meters: 5.0,
        cost_fabric: 225.0,
        cost_foam: 0.0,
        cost_labor: 150.0,
        cost_shipping: 20.0,
        cost_other: 80.0,
        total_cost: 475.0,
        final_price: 800.0,
        net_profit: 325.0,
        collection_date: new Date('2026-03-03'),
        status: ServiceStatus.IN_PROGRESS,
      },
      {
        client_id: client4.id,
        furniture_name: 'Canto Alemão',
        fabric_name: 'Acquablock Floral',
        fabric_code: 'AQ-FL',
        fabric_price_per_meter: 65.0,
        fabric_meters: 7.0,
        cost_fabric: 455.0,
        cost_foam: 180.0,
        cost_labor: 500.0,
        cost_shipping: 70.0,
        cost_other: 30.0,
        total_cost: 1235.0,
        final_price: 2100.0,
        net_profit: 865.0,
        collection_date: new Date('2025-11-01'),
        delivery_date: new Date('2025-11-15'),
        status: ServiceStatus.PAID,
        notes: 'Tecido impermeável para área gourmet.',
      },
      {
        client_id: client4.id,
        furniture_name: 'Banquetas de Balcão (3x)',
        fabric_name: 'Corino Preto',
        fabric_code: 'CR-PR',
        fabric_price_per_meter: 25.0,
        fabric_meters: 2.0,
        cost_fabric: 50.0,
        cost_foam: 45.0,
        cost_labor: 120.0,
        cost_shipping: 30.0,
        cost_other: 10.0,
        total_cost: 255.0,
        final_price: 500.0,
        net_profit: 245.0,
        collection_date: new Date('2026-01-20'),
        delivery_date: new Date('2026-02-05'),
        status: ServiceStatus.DELIVERED,
      },
      {
        client_id: client4.id,
        furniture_name: 'Sofá Chesterfield',
        fabric_name: 'Couro Envelhecido',
        fabric_code: 'CE-BR',
        fabric_price_per_meter: 180.0,
        fabric_meters: 15.0,
        cost_fabric: 2700.0,
        cost_foam: 300.0,
        cost_labor: 1500.0,
        cost_shipping: 200.0,
        cost_other: 150.0,
        total_cost: 4850.0,
        final_price: 8500.0,
        net_profit: 3650.0,
        collection_date: new Date('2026-03-01'),
        status: ServiceStatus.IN_PROGRESS,
      },
      {
        client_id: client5.id,
        furniture_name: 'Cadeiras de Escritório (2x)',
        fabric_name: 'Tela Mesh',
        fabric_code: 'TM-PR',
        fabric_price_per_meter: 50.0,
        fabric_meters: 3.0,
        cost_fabric: 150.0,
        cost_foam: 60.0,
        cost_labor: 200.0,
        cost_shipping: 40.0,
        cost_other: 20.0,
        total_cost: 470.0,
        final_price: 850.0,
        net_profit: 380.0,
        collection_date: new Date('2025-05-10'),
        delivery_date: new Date('2025-05-18'),
        status: ServiceStatus.PAID,
      },
      {
        client_id: client5.id,
        furniture_name: 'Chaise Longue',
        fabric_name: 'Veludo Rosê',
        fabric_code: 'VL-RS',
        fabric_price_per_meter: 70.0,
        fabric_meters: 6.0,
        cost_fabric: 420.0,
        cost_foam: 150.0,
        cost_labor: 450.0,
        cost_shipping: 80.0,
        cost_other: 40.0,
        total_cost: 1140.0,
        final_price: 2000.0,
        net_profit: 860.0,
        collection_date: new Date('2026-02-20'),
        status: ServiceStatus.COMPLETED,
      },
      {
        client_id: client5.id,
        furniture_name: 'Futon Japonês',
        fabric_name: 'Sarja Peletizada',
        fabric_code: 'SJ-CR',
        fabric_price_per_meter: 40.0,
        fabric_meters: 8.0,
        cost_fabric: 320.0,
        cost_foam: 250.0,
        cost_labor: 300.0,
        cost_shipping: 60.0,
        cost_other: 30.0,
        total_cost: 960.0,
        final_price: 1600.0,
        net_profit: 640.0,
        collection_date: new Date('2026-02-25'),
        delivery_date: new Date('2026-03-04'),
        status: ServiceStatus.DELIVERED,
      },
    ],
  });

  console.log('✅ Seed finalizado com sucesso!');
}

main()
  .catch((e) => {
    console.error('❌ Erro durante o seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
